---
# iNSTALLING wINDOWS ad

  - name: install windows AD
    win_feature:
      name: AD-Domain-Services
      state: present
  - win_domain:
      dns_domain_name: "{{ad_domain_name}}"
      safe_mode_password: "{{ad_safe_mode_password}}"
    register: result
  - win_reboot: 
      reboot_timeout_sec: 3600
    when: result.reboot_required
  - name: Prints out the domain list
    win_shell: nltest /dclist:"{{ad_domain_name}}"
    register: domain_list
  - debug:
      var: domain_list
