---
#Supposedly good playbook
- name: configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - repo

- name: deploy haproxy
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - haproxy

- name: deploy tomcat and copy index.html
  hosts: apps
  gather_facts: true
  become: true
  roles:
    - tomcat
    - index_setup