---
#A role to copy over the repos to all the servers.
  - name: enable repos
    template:
      src: files/open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644
