---
# Creating Win SSH service

    - name: gather_facts
      gather_facts: true
    - win_chocolatey: name={{ item }} state=installed
        with_items:
          - "{{ package_name }}"
      when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
    - name: Restart a service
    - win_service:
        name: "{{ service_name }}"
        state: restarted
      when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
    - name: Firewall rule to allow RDP on TCP port 3389
      win_firewall_rule:
            name: "{{ service_name }}"
            localport: "{{ local_port }}"
            action: allow
            direction: in
            protocol: "{{ protocol_name }}"
            state: present
            enabled: yes