---
# This role will install Postgres DB
  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: Start Postgres service
    service:
      name: postgresql
      enabled: yes
  - name: tell user to finish setting up postgres
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

# only run the next 2 tasks once!
  - name: initilize postgres
    command: postgresql-setup initdb
  - name: initilize postgres some more
    command: chkconfig postgresql on